### ISSUE TITLE
DjangoとDBコンテナのUnknown columnエラー

### ISSUE THREAD

**Issue by Kazumasa1** [Kazumasa1/memo-re#82]
Django コンテナを起動したら、DBのエラーが出ました。
```
Traceback (most recent call last):
  File "/usr/src/app/app/manage.py", line 22, in <module>
    main()
  File "/usr/src/app/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/imagekit/management/commands/generateimages.py", line 30, in handle
    for image_file in cachefile_registry.get(generator_id):
  File "/usr/local/lib/python3.9/site-packages/imagekit/registry.py", line 155, in get
    for file in k():
  File "/usr/local/lib/python3.9/site-packages/imagekit/specs/sourcegroups.py", line 170, in __call__
    for source_file in self.source_group.files():
  File "/usr/local/lib/python3.9/site-packages/imagekit/specs/sourcegroups.py", line 146, in files
    for instance in model.objects.all().iterator():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 353, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'custom_user.id' in 'field list'")
```

**Comment by Kazumasa1** [comment]
ビルド時に`0001_initial.py`が生成されていて、ここが古いままでした。
なので、`docker compose build --no-cache`の前に`0001_initial.py`を削除してから実行でうまくいきました。
![0001_initial](https://user-images.githubusercontent.com/70145199/210359004-081907c9-abf7-48c9-9701-9786a327b800.png)

**Comment by Kazumasa1** [comment]
将来的には、`docker compose build --no-cache`で既存の`0001_initial.py`を削除する処理を追加したい。
